# Generated by Django 3.2.4 on 2021-06-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customername',
            new_name='name',
        ),
    ]
